[project]
name = "workflow-creator"
version = "0.1.0"
description = "A Streamlit GUI for creating and managing workflows"
dependencies = [
    "streamlit>=1.32.0",
    "pydantic>=2.6.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
